title = "Notre-Dame de Paris"
baseURL = "https://gohugo-theme-ananke.pages.dev"
languageCode = "it-it"
theme = ["ananke"]
resourceDir = "../resources"

DefaultContentLanguage = "it"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true


[languages]

  [languages.it]
    title = "Lorenzo Scarpelli"
    weight = 1
    contentDir = "content/it"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  contactemail = "info@lorenzoscarpelli.eu"

  [[params.plugins.css]]
  link = "/bootstrap/dist/css/bootstrap.min.css"
  [[params.plugins.css]]
  link = "/style.css"

  [[params.plugins.js]]
  link="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
  [[params.plugins.js]]
  link = "/bootstrap/dist/js/bootstrap.bundle.min.js"
  [[params.plugins.js]]
  link = "/jquery/jquery.min.js"
  [[params.plugins.js]]
  link = "/custom/queries.js"


#[[params.ananke_socials]]
#name = "twitter"
#url = "https://twitter.com/GoHugoIO"
